name: graphql_sample_kaigi_2021
description: GraphQL sample project for flutter kaigi 2021.

version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # graphql
  ferry:
  gql_link:
  gql_http_link:
  ferry_flutter:
  # persistent cache
  ferry_hive_store:
  hive:
  hive_flutter:
  # architecture
  flutter_riverpod:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  ferry_generator:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
